# Generated by Django 4.2 on 2025-02-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('csrftoken', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='CSRF令牌')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
            ],
        ),
    ]
