# Generated by Django 4.2 on 2025-02-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0002_envelope_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='账户余额'),
        ),
    ]
