# Generated by Django 4.2 on 2025-02-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0004_remove_envelope_a_alter_envelope_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='csrftoken',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='CSRF令牌'),
        ),
    ]
