# Generated by Django 4.2 on 2025-03-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0005_alter_envelope_csrftoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(verbose_name='红包总钱数')),
                ('total_people', models.IntegerField(verbose_name='总人数')),
                ('received_total_people', models.IntegerField(verbose_name='领取总人数')),
            ],
        ),
        migrations.RenameModel(
            old_name='Envelope',
            new_name='UserEnvelope',
        ),
    ]
