# Generated by Django 4.2 on 2025-03-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0006_publicenvelope_rename_envelope_userenvelope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicenvelope',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='红包总钱数'),
        ),
    ]
