# Generated by Django 4.2 on 2025-03-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0007_alter_publicenvelope_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicenvelope',
            name='word',
            field=models.CharField(default='', max_length=100, verbose_name='祝福语'),
        ),
    ]
