# Generated by Django 4.2 on 2025-04-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0010_alter_publicenvelope_per_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicenvelope',
            name='per_person',
            field=models.TextField(default='', verbose_name='每人领取钱数的列表'),
        ),
    ]
