# Generated by Django 4.2 on 2025-04-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0011_alter_publicenvelope_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicenvelope',
            name='csrftoken',
            field=models.CharField(default='', max_length=50, verbose_name='CSRF令牌'),
        ),
    ]
