# Generated by Django 4.2 on 2025-04-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0012_publicenvelope_csrftoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicenvelope',
            old_name='csrftoken',
            new_name='publisher',
        ),
    ]
