# Generated by Django 4.2 on 2025-04-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0013_rename_csrftoken_publicenvelope_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicenvelope',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='是否领完'),
        ),
    ]
