# Generated by Django 4.2 on 2025-04-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0014_publicenvelope_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicenvelope',
            name='received_total_people',
            field=models.IntegerField(default=0, verbose_name='领取总人数'),
        ),
    ]
