# Generated by Django 4.2 on 2025-05-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0015_alter_publicenvelope_received_total_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenvelope',
            name='received_envs_id',
            field=models.TextField(default='', verbose_name='用户领取过红包的ID'),
        ),
    ]
