# Generated by Django 4.2 on 2025-05-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0016_userenvelope_received_envs_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userenvelope',
            old_name='received_envs_id',
            new_name='received_envs_ids',
        ),
    ]
