# Generated by Django 4.2 on 2025-05-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0017_rename_received_envs_id_userenvelope_received_envs_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenvelope',
            name='nickname',
            field=models.CharField(default='', max_length=50, verbose_name='用户昵称'),
        ),
    ]
