# Generated by Django 4.2 on 2025-05-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0018_userenvelope_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenvelope',
            name='nickname',
            field=models.TextField(default='', verbose_name='用户昵称'),
        ),
    ]
