# Generated by Django 4.2 on 2025-05-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0019_alter_userenvelope_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenvelope',
            name='nickname',
            field=models.CharField(default='', max_length=50, verbose_name='用户昵称'),
        ),
    ]
