# Generated by Django 5.2.1 on 2025-05-31 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0020_alter_userenvelope_nickname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEnvelope',
            new_name='Users',
        ),
    ]
