# Generated by Django 5.2.1 on 2025-07-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0021_rename_userenvelope_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_csrftoken', models.CharField(max_length=50, verbose_name='CSRF令牌')),
                ('to_csrftoken', models.CharField(max_length=50, verbose_name='CSRF令牌')),
            ],
        ),
    ]
