# Generated by Django 5.2.1 on 2025-07-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0022_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='session_uuid',
            field=models.CharField(default='', max_length=50, verbose_name='UUID'),
        ),
    ]
