# Generated by Django 5.2.4 on 2025-08-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PChat', '0023_calls_session_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('csrftoken', models.CharField(max_length=50, verbose_name='CSRF令牌')),
            ],
        ),
    ]
